
package learn.admin_sub.newBook;
import java.sql.*;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import learn.Admin_menu;

public class oldIsbn extends javax.swing.JFrame {
    private Connection connect = null;
    private Statement statement = null;
    private PreparedStatement preparedStatement = null;
    private ResultSet resultSet = null;
    JOptionPane op = new JOptionPane();
    JDialog dia = null;
    /**
     * Creates new form oldIsbn
     */
    public oldIsbn() {
        initComponents();
        addList();
    }
    
    public void addList(){
        try{
        Class.forName("com.mysql.jdbc.Driver");
      // setup the connection with the DB.
       connect = DriverManager
          .getConnection("jdbc:mysql://localhost/library?"
              + "user=name&password=password");

      // statements allow to issue SQL queries to the database
        statement = connect.createStatement();
        preparedStatement = connect.prepareStatement("select isbn from book_info;");
      resultSet = preparedStatement.executeQuery();
      while(resultSet.next())
      {
          String s = resultSet.getString("isbn");
          isbn.addItem(s.trim());
      }
        }catch(Exception e){
            
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        isbn = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        branch_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        position = new javax.swing.JTextField();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ISBN :");

        isbn.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select"}));

        jLabel2.setText("Branch Name :");

        jLabel3.setText("Position :");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branch_name, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(position))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(branch_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(submit)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String name = branch_name.getText().toString();
        int s;
        try{
        Class.forName("com.mysql.jdbc.Driver");
      // setup the connection with the DB.
       connect = DriverManager
          .getConnection("jdbc:mysql://localhost/library?"
              + "user=name&password=password");

      // statements allow to issue SQL queries to the database
        statement = connect.createStatement();
        preparedStatement = connect.prepareStatement("select branch_id from branch where name=?;");
        preparedStatement.setString(1,name);
        resultSet = preparedStatement.executeQuery();
      while(resultSet.next())
      {
          s = resultSet.getInt("branch_id");  
          preparedStatement = connect.prepareStatement("insert into book(isbn, branch_id, position)"
                + " values(?,?,?);");
          preparedStatement.setString(1, isbn.getSelectedItem().toString());
          preparedStatement.setInt(2, s);
          preparedStatement.setString(3, position.getText());
          preparedStatement.executeUpdate();
          preparedStatement = connect.prepareStatement("select * from copy where isbn="
                  + "'"+isbn.getSelectedItem().toString()+"' and branch_id="+s+";");
          resultSet=preparedStatement.executeQuery();
          if(!resultSet.next()){
              preparedStatement=connect.prepareStatement("insert into copy(isbn, branch_id, copies)"
                      + " values(?, ?, ?);");
              preparedStatement.setString(1, isbn.getSelectedItem().toString());
              preparedStatement.setInt(2, s);
              preparedStatement.setInt(3, 1);
              preparedStatement.executeUpdate();
          }
          else{
          preparedStatement = connect.prepareStatement("update copy set copies=copies+1 "
              + "where branch_id=? and isbn=?;");
          preparedStatement.setInt(1, s);
          preparedStatement.setString(2, isbn.getSelectedItem().toString() );
          preparedStatement.executeUpdate();
          }
          op.setMessage("New Copy has been added");
          op.setMessageType(1);
          dia = op.createDialog("Success");
          dia.setVisible(true);
          dispose();
          Admin_menu af = new Admin_menu();
          af.setVisible(true);
      }
       }catch(Exception e){
            
        }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oldIsbn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oldIsbn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oldIsbn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oldIsbn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oldIsbn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField branch_name;
    private javax.swing.JComboBox isbn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField position;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
