package learn.reader_sub;
import java.sql.*;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JDialog;

public class ComputeFines extends javax.swing.JFrame {
    int reader_id;
    private Connection connect = null;
    private Statement statement = null;
    private PreparedStatement preparedStatement = null;
    private ResultSet resultSet = null;
    private JOptionPane op = new JOptionPane();
    private JDialog dia = null;
    /**
     * Creates new form ComputeFines
     */
    public ComputeFines() {
        initComponents();
    }
    public ComputeFines(int r) {
        initComponents();
        reader_id = r;
        addBook();
    }
    private void addBook(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager
          .getConnection("jdbc:mysql://localhost/library?"
              + "user=name&password=password");
            statement = connect.createStatement();
            preparedStatement = connect.prepareStatement("select book_id from borrow "
                    + "where reader_id="+reader_id+" and return_date is NULL;");
            resultSet = preparedStatement.executeQuery();
            while(resultSet.next()){
                int i = resultSet.getInt("book_id");
                book_id.addItem(i);
            }
        }catch(Exception e){
            
        }
    }
    private int calculateDays(Date a,Date b)
    {
        Integer rmonth = new Integer(a.toString().substring(5, 7));
        Integer bmonth = new Integer(b.toString().substring(5, 7));
        Integer rday = new Integer(a.toString().substring(8));
        Integer bday = new Integer(b.toString().substring(8));
        int i=0;
        if(rmonth.equals(bmonth)){
            if(rday-bday <= 15)
                return 0;
            else
                return rday-bday-15;
        }
        else
        { 
            i = rmonth - bmonth;
            if(i==1){
                if(bmonth == 1 || bmonth == 3 || bmonth==5 || bmonth==7 || bmonth==8 || bmonth==10){
                    if(31-bday+rday-15 < 0)
                        return 0;
                    else
                        return 31-bday+rday-15;}
                else{
                    if(31-bday+rday-15 < 0)
                        return 0;
                    else
                        return 31-bday+rday-15;}
            }
            return 50;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        book_id = new javax.swing.JComboBox();
        calculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fines");

        jLabel2.setText("Book Id :");

        book_id.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(book_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(calculate)
                        .addGap(155, 155, 155))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(book_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(calculate)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
       Date date = new Date();
       java.sql.Date sqlDate = new java.sql.Date(date.getTime());
       java.sql.Date bd = null;
       int j=0;
       try{
           preparedStatement = connect.prepareStatement("select borrow_date from "
                    + "borrow where book_id="+book_id.getSelectedItem()+" and reader_id="+reader_id+";");
            resultSet = preparedStatement.executeQuery();
            while(resultSet.next()){
                bd = resultSet.getDate("borrow_date");
                j = calculateDays(sqlDate, bd);
            }
            op.setMessage("Fine for Book id:"+book_id.getSelectedItem()+" borrowed "
                    + "on "+bd+" is $"+Math.round(j*0.1*100.0)/100.0);
            op.setMessageType(1);
            dia = op.createDialog("Calculated Fine");
            dia.setVisible(true);
       }catch(Exception e){
           op.setMessage(e.getMessage());
            op.setMessageType(0);
            dia = op.createDialog("Error");
            dia.setVisible(true);
       }
    }//GEN-LAST:event_calculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputeFines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputeFines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputeFines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputeFines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputeFines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox book_id;
    private javax.swing.JButton calculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
